services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: bistagram-mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: bistagram
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-test-vol:/var/lib/mysql

  api:
    build:
      context: ./backend/
      target: fast
    container_name: fastapi-application
    ports:
      - 9512:80
    restart: "always"


  web:
    build: ./frontend
    container_name: bistagram-frontend
    ports:
      - "127.0.0.1:5173:5173"
    # volumes:
    #   - .:/app
volumes:
  mysql-test-vol:
